{% set name = "hapsira" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3a10eb08ec63544c2db147bae47cbf1b72706a5b25670d25ca598fdcadae8f3c

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
    - flit

  run:
    - python >=3.8
    - numpy >=1.10
    - scipy >=1.4
    - numba >=0.53.0
    - astropy-base >=5.0,<6
    - jplephem
    - matplotlib-base >=2.0,!=3.0.1
    - plotly >=4.0,<6
    - astroquery >=0.3.9
    - cached-property
    - pyerfa
    - czml3

test:
  imports:
    - hapsira
    - hapsira.constants
    - hapsira.twobody
    - hapsira.threebody
    - hapsira.iod
    - hapsira.frames
    - hapsira.plotting
    - hapsira.ephem

about:
  home: https://hapsira.readthedocs.io/
  license: MIT
  license_file: LICENSE
  summary: "Astrodynamics in Python - a poliastro fork"

extra:
  recipe-maintainers:
    - s-m-e
